version: '3'
services:
  proxy:
    image: nginx:latest
    hostname: proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./proxy/conf:/etc/nginx/conf.d
      - ./proxy/ssl:/etc/ssl/private
    environment:
      TZ: Europe/Vienna
    restart: unless-stopped
    profiles:
      - full
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'CHANGEME'
      POSTGRES_DB: 'citadel'
      TZ: Europe/Vienna
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - full
  postgres-dev:
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'CHANGEME'
      POSTGRES_DB: 'citadel'
      TZ: Europe/Vienna
    ports:
      - '127.0.0.1:5432:5432'
    restart: unless-stopped
    profiles:
      - dev
  astro:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    hostname: astro
    environment:
      INSTANCE_NAME: 'testCTF'
      EMAIL_SERVICE: 'hotmail'
      EMAIL_NAME: 'someone@example.com'
      EMAIL_PASS: 'CHANGEME'
      DB_HOST: 'postgres'
      DB_NAME: 'citadel'
      DB_USER: 'root'
      DB_PASS: 'CHANGEME'
      BACKEND_HOST: '127.0.0.1'
      BACKEND_PORT: 8080
      TZ: Europe/Vienna
    restart: unless-stopped
    profiles:
      - full
