version: '3'
services:
  postgres-dev:
    image: docker.io/library/postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'CHANGEME'
      POSTGRES_DB: 'citadel'
      TZ: Europe/Vienna
    ports:
      - '127.0.0.1:5432:5432'
    restart: unless-stopped
    profiles:
      - dev
