version: '3'
services:
  # Proxy
  nginx:
    image: docker.io/library/nginx:latest
    hostname: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/private
    environment:
      TZ: Europe/Vienna
    restart: unless-stopped
    profiles:
      - full
      - standalone
      - anticheat
      - firstblood
  # WebApp
  postgres-webapp:
    image: docker.io/library/postgres:latest
    hostname: postgres-webapp
    environment:
      TZ: Europe/Vienna
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'CHANGEME'
      POSTGRES_DB: 'webapp'
    volumes:
      - ./data/postgres-webapp:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - full
      - standalone
      - anticheat
      - firstblood
  webapp:
    image: ghcr.io/ctf-citadel/webapp:latest
    hostname: webapp
    volumes:
      - ./config.toml:/config/config.toml
      - ./webapp:/data
    environment:
      TZ: Europe/Vienna
      DB_HOST: 'postgres-webapp'
      DB_NAME: 'webapp'
      DB_USER: 'root'
      DB_PASS: 'CHANGEME'
    restart: unless-stopped
    profiles:
      - full
      - standalone
      - anticheat
      - firstblood
  # AntiCheat
  postgres-m0n1t0r:
    image: docker.io/library/postgres:latest
    hostname: postgres-m0n1t0r
    environment:
      TZ: Europe/Vienna
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'CHANGEME'
      POSTGRES_DB: 'm0n1t0r'
    volumes:
      - ./data/postgres-m0n1t0r:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - full
      - anticheat
  m0n1t0r:
    image: ghcr.io/ctf-citadel/m0n1t0r:latest
    hostname: m0n1t0r
    environment:
      TZ: Europe/Vienna
      DB_NAME: 'm0n1t0r'
      DB_HOST: 'postgres-m0n1t0r'
      DB_USER: 'root'
      DB_PW: 'CHANGEME'
    restart: unless-stopped
    profiles:
      - full
      - anticheat
  # Reporter
  f1rstbl00d:
    image: ghcr.io/ctf-citadel/f1rstbl00d:latest
    hostname: f1rstbl00d
    environment:
      TZ: Europe/Vienna
      BLOODTOKEN: 'CHANGEME'
      DISCORD_TOKEN: 'CHANGEME'
      DISCORD_CHANNEL_ID: 1234567890
    volumes:
      - ./data/sqlite-f1rstbl00d:/app/data
    profiles:
      - full
      - firstblood
